"""VOIDWAVE Cyberpunk Theme Constants."""

# Color Palette
NEON_CYAN = "#0ABDC6"
HOT_MAGENTA = "#EA00D9"
DEEP_NAVY = "#091833"
DARK_SURFACE = "#1A1A2E"
MATRIX_GREEN = "#00FF41"
NEON_ORANGE = "#FF9A00"
CORAL_RED = "#FF0040"
LIGHT_GRAY = "#E0E0E0"
MUTED_GRAY = "#808080"
CYAN_BORDER = "#0ABDC6"
DIM_CYAN = "#065A5F"

# Status Colors
STATUS_IDLE = MUTED_GRAY
STATUS_RUNNING = NEON_CYAN
STATUS_SUCCESS = MATRIX_GREEN
STATUS_WARNING = NEON_ORANGE
STATUS_ERROR = CORAL_RED

# Severity Colors
SEVERITY_CRITICAL = CORAL_RED
SEVERITY_HIGH = NEON_ORANGE
SEVERITY_MEDIUM = "#FFD700"  # Gold
SEVERITY_LOW = NEON_CYAN
SEVERITY_INFO = MUTED_GRAY

# Signal Strength Colors
SIGNAL_EXCELLENT = MATRIX_GREEN
SIGNAL_GOOD = "#7FFF00"  # Chartreuse
SIGNAL_FAIR = NEON_ORANGE
SIGNAL_POOR = CORAL_RED

# Encryption Colors
ENCRYPTION_OPEN = CORAL_RED
ENCRYPTION_WEP = NEON_ORANGE
ENCRYPTION_WPA = NEON_CYAN
ENCRYPTION_WPA2 = MATRIX_GREEN
ENCRYPTION_WPA3 = HOT_MAGENTA
